module.exports = [
  {
    id: 1,
    icon: 'laptop',
    name: '项目统计',
    router: '/dashboard',
  },
  {
    id: 2,
    bpid: 1,
    name: '用户信息',
    icon: 'user',
    router: '/user',
  },
  {
    id: 7,
    bpid: 1,
    name: '用户提交',
    icon: 'shopping-cart',
    router: '/post',
  },
  {
    id: 21,
    mpid: -1,
    bpid: 2,
    name: '详细信息',
    router: '/user/:id',
  },
  {
    id: 3,
    bpid: 1,
    name: '请求',
    icon: 'api',
    router: '/request',
  },
  {
    id: 4,
    bpid: 1,
    name: 'UI组件',
    icon: 'camera-o',
  },
  {
    id: 41,
    bpid: 4,
    mpid: 4,
    name: '图标字体',
    icon: 'heart-o',
    router: '/UIElement/iconfont',
  },
  {
    id: 42,
    bpid: 4,
    mpid: 4,
    name: '数据表格',
    icon: 'database',
    router: '/UIElement/dataTable',
  },
  {
    id: 43,
    bpid: 4,
    mpid: 4,
    name: '下拉选项',
    icon: 'bars',
    router: '/UIElement/dropOption',
  },
  {
    id: 44,
    bpid: 4,
    mpid: 4,
    name: '查询',
    icon: 'search',
    router: '/UIElement/search',
  },
  {
    id: 45,
    bpid: 4,
    mpid: 4,
    name: '编辑',
    icon: 'edit',
    router: '/UIElement/editor',
  },
  {
    id: 46,
    bpid: 4,
    mpid: 4,
    name: 'layer (Function)',
    icon: 'credit-card',
    router: '/UIElement/layer',
  },
  {
    id: 5,
    bpid: 1,
    name: '图表',
    icon: 'code-o',
  },
  {
    id: 51,
    bpid: 5,
    mpid: 5,
    name: '折线图',
    icon: 'line-chart',
    router: '/chart/lineChart',
  },
  {
    id: 52,
    bpid: 5,
    mpid: 5,
    name: '柱状图',
    icon: 'bar-chart',
    router: '/chart/barChart',
  },
  {
    id: 53,
    bpid: 5,
    mpid: 5,
    name: '块状图',
    icon: 'area-chart',
    router: '/chart/areaChart',
  },
  {
    id: 6,
    bpid: 1,
    name: 'Test Navigation',
    icon: 'setting',
  },
  {
    id: 61,
    bpid: 6,
    mpid: 6,
    name: 'Test Navigation1',
    router: '/navigation/navigation1',
  },
  {
    id: 62,
    bpid: 6,
    mpid: 6,
    name: 'Test Navigation2',
    router: '/navigation/navigation2',
  },
  {
    id: 621,
    bpid: 62,
    mpid: 62,
    name: 'Test Navigation21',
    router: '/navigation/navigation2/navigation1',
  },
  {
    id: 622,
    bpid: 62,
    mpid: 62,
    name: 'Test Navigation22',
    router: '/navigation/navigation2/navigation2',
  },
]
